version: '2'
# starts 4 docker containers running minio server instances. Each minio server's web interface will be accessible on the host at port 9001 through 9004.
services:
  minio1:
    image: minio/minio
    volumes:
      - /srv/node/sdb/minio1/data:/data
    ports:
      - "9001:9000"
      - "9091:9090"
    environment:
      MINIO_ACCESS_KEY: 4zB82roDUioFIyiHsMF9
      MINIO_SECRET_KEY: Y7qz3rz6Wgpviitiq2v3um2OaS760vCGg5I1MNES
    networks:
      - minio-net
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data --console-address ":9090"
    
  minio2:
    image: minio/minio
    volumes:
      - /srv/node/sdb/minio2/data:/data
    ports:
      - "9002:9000"
      - "9092:9090"
    environment:
      MINIO_ACCESS_KEY: 4zB82roDUioFIyiHsMF9
      MINIO_SECRET_KEY: Y7qz3rz6Wgpviitiq2v3um2OaS760vCGg5I1MNES
    networks:
      - minio-net
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data --console-address ":9090"
    
  minio3:
    image: minio/minio
    volumes:
      - /srv/node/sdb/minio3/data:/data
    ports:
      - "9003:9000"
      - "9093:9090"
    environment:
      MINIO_ACCESS_KEY: 4zB82roDUioFIyiHsMF9
      MINIO_SECRET_KEY: Y7qz3rz6Wgpviitiq2v3um2OaS760vCGg5I1MNES
    networks:
      - minio-net
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data --console-address ":9090"
    
  minio4:
    image: minio/minio
    volumes:
      - /srv/node/sdb/minio4/data:/data
    ports:
      - "9004:9000"
      - "9094:9090"
    environment:
      MINIO_ACCESS_KEY: 4zB82roDUioFIyiHsMF9
      MINIO_SECRET_KEY: Y7qz3rz6Wgpviitiq2v3um2OaS760vCGg5I1MNES
    networks:
      - minio-net
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data --console-address ":9090"

  minio_nginx:
    image: nginx:latest
    restart: always
    ports:
      - 9000:80
      - 9090:81
    volumes:
      - ~/minio/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ~/minio/nginx/minio.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - minio1
      - minio2
      - minio3
      - minio4
    networks:
      - minio-net

networks:
  minio-net:
    driver: bridge


